image: docker:latest
    
services:
  - docker:dind   

stages: 
    - test
  
test_server:
    stage: test
    script:
        - apk add --no-cache docker-compose
        - docker-compose --file docker-compose.test.yml up --build --abort-on-container-exit