version: '3.1'

services:
  db:
    image: 'postgres'
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
    environment:
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_DB: ${TYPEORM_DATABASE}
    container_name: fliness_messenger_database_test
  api:
    user: api
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - ${PORT}:${PORT}
    environment:
      TYPEORM_HOST: 'db'
      PORT: ${PORT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      TYPEORM_CONNECTION: ${TYPEORM_CONNECTION}
      TYPEORM_USERNAME: ${TYPEORM_USERNAME}
      TYPEORM_PASSWORD: ${TYPEORM_PASSWORD}
      TYPEORM_DATABASE: ${TYPEORM_DATABASE}
      TYPEORM_PORT: ${TYPEORM_PORT}
      TYPEORM_SYNCHRONIZE: ${TYPEORM_SYNCHRONIZE}
      TYPEORM_ENTITIES: ${TYPEORM_ENTITIES}
      TYPEORM_SUBSCRIBERS: ${TYPEORM_SUBSCRIBERS}
      TRAVIS_JOB_ID: ${TRAVIS_JOB_ID}
      TRAVIS_BRANCH: ${TRAVIS_BRANCH}
    depends_on:
      - db
    volumes:
      - .:/usr/src/fliness-messenger-api
      - node_modules:/usr/src/fliness-messenger-api/node_modules
    container_name: fliness_messenger_api_test

volumes:
  node_modules:
