version: '3.1'

services: 
    db:
        env_file: .env.test
        image: 'postgres'
        ports:
            - ${TYPEORM_PORT}:${TYPEORM_PORT}
        environment: 
            POSTGRES_USER: ${TYPEORM_USERNAME}
            POSTGRES_PASSWORD: ${TYPEORM_PASSWORD} 
            POSTGRES_DB: ${TYPEORM_DATABASE}
        restart: always
        container_name: fliness_messenger_database_test
    api:
        build: 
            context: .
            dockerfile: Dockerfile.test
        ports:
            - ${PORT}:${PORT}
        env_file: .env.test
        environment: 
            TYPEORM_HOST: 'db'
        depends_on:
            - db
        volumes: 
            - .:/usr/src/fliness-messenger-api
            - node_modules:/usr/src/fliness-messenger-api/node_modules
        restart: always
        container_name: fliness_messenger_api_test

volumes: 
    node_modules: