FROM node

ARG path=/usr/src/fliness-messenger-api
RUN mkdir ${path}
WORKDIR ${path}

RUN npm install -g @nestjs/cli

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE ${PORT}

CMD npm run build && npm run db:init && npm run db:seeds:run && npm run start:dev